export const chatMessages = [
  {
    id: "1",
    text: "Hey! How's your day going?",
    sender: "contact",
    time: "10:30 AM",
  },
  {
    id: "2",
    text: "Hi Sarah! It's going great, thanks for asking. Just finished a big project at work 🎉",
    sender: "user",
    time: "10:32 AM",
  },
  {
    id: "3",
    text: "That's awesome! Congratulations! 🎊 What was the project about?",
    sender: "contact",
    time: "10:33 AM",
  },
  {
    id: "4",
    text: "Thanks! It was a chat application - actually pretty similar to this one we're using right now 😄",
    sender: "user",
    time: "10:35 AM",
  },
  {
    id: "5",
    text: "Wow, that's so cool! I'd love to see it sometime. Building chat apps must be really interesting.",
    sender: "contact",
    time: "10:36 AM",
  },
  {
    id: "6",
    text: "Absolutely! There's so much that goes into making them feel smooth and intuitive. The real-time messaging, the UI/UX design, all the little details that make communication feel natural.",
    sender: "user",
    time: "10:38 AM",
  },
  {
    id: "7",
    text: "I can imagine! Speaking of which, this interface looks really clean and modern. Great job on the design! 👏",
    sender: "contact",
    time: "10:40 AM",
  },
  {
    id: "1",
    text: "Hey! How's your day going?",
    sender: "contact",
    time: "10:30 AM",
  },
  {
    id: "2",
    text: "Hi Sarah! It's going great, thanks for asking. Just finished a big project at work 🎉",
    sender: "user",
    time: "10:32 AM",
  },
  {
    id: "3",
    text: "That's awesome! Congratulations! 🎊 What was the project about?",
    sender: "contact",
    time: "10:33 AM",
  },
  {
    id: "4",
    text: "Thanks! It was a chat application - actually pretty similar to this one we're using right now 😄",
    sender: "user",
    time: "10:35 AM",
  },
  {
    id: "5",
    text: "Wow, that's so cool! I'd love to see it sometime. Building chat apps must be really interesting.",
    sender: "contact",
    time: "10:36 AM",
  },
  {
    id: "6",
    text: "Absolutely! There's so much that goes into making them feel smooth and intuitive. The real-time messaging, the UI/UX design, all the little details that make communication feel natural.",
    sender: "user",
    time: "10:38 AM",
  },
  {
    id: "7",
    text: "I can imagine! Speaking of which, this interface looks really clean and modern. Great job on the design! 👏",
    sender: "contact",
    time: "10:40 AM",
  },
  {
    id: "1",
    text: "Hey! How's your day going?",
    sender: "contact",
    time: "10:30 AM",
  },
  {
    id: "2",
    text: "Hi Sarah! It's going great, thanks for asking. Just finished a big project at work 🎉",
    sender: "user",
    time: "10:32 AM",
  },
  {
    id: "3",
    text: "That's awesome! Congratulations! 🎊 What was the project about?",
    sender: "contact",
    time: "10:33 AM",
  },
  {
    id: "4",
    text: "Thanks! It was a chat application - actually pretty similar to this one we're using right now 😄",
    sender: "user",
    time: "10:35 AM",
  },
  {
    id: "5",
    text: "Wow, that's so cool! I'd love to see it sometime. Building chat apps must be really interesting.",
    sender: "contact",
    time: "10:36 AM",
  },
  {
    id: "6",
    text: "Absolutely! There's so much that goes into making them feel smooth and intuitive. The real-time messaging, the UI/UX design, all the little details that make communication feel natural.",
    sender: "user",
    time: "10:38 AM",
  },
  {
    id: "7",
    text: "I can imagine! Speaking of which, this interface looks really clean and modern. Great job on the design! 👏",
    sender: "contact",
    time: "10:40 AM",
  },
];
